# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cc2b1ca8d48d873f6abc6d52dc7511299d4e329ec202337726ec783aab82ff46346c50f2e9adbd55648f60ca0757804de44e0606d62848b55703e08fe449eee

test:
  secret_key_base: 186503e08141a8a9e0ea1cc75f504d3754568bfea2c7be662dcc86f051ed1fa0c9d915ca3b0779d8a7f314d77bd076f478d3d6da6b1cf4545801360fb83685af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
